### ISSUE TITLE
UAST filtering/marshalling randomly panics

### ISSUE THREAD

**Issue by erizocosmico** [bblfsh/client-go#60]
Some files panic randomly while using `tools.Filter` or `node.Marshal`

Reproduction case:

```go
func TestBblfshFailing(t *testing.T) {
	xpath := `//*[@roleFunction and @roleDeclaration]`
	code := `package hdfs

import (
        "bytes"
        "encoding/hex"
        "hash/crc32"
        "io"
        "io/ioutil"
        "math/rand"
        "os"
        "testing"
        "time"

        "github.com/stretchr/testify/assert"
        "github.com/stretchr/testify/require"
)

const (
        // many grep -b died to bring us this information...
        testStr    = "Abominable are the tumblers into which he pours his poison."
        testStrOff = 48847

        testStr2            = "http://www.gutenberg.org"
        testStr2Off         = 1256988
        testStr2NegativeOff = -288

        testChecksum = "27c076e4987344253650d3335a5d08ce"
)

func TestFileRead(t *testing.T) {
        client := getClient(t)

        file, err := client.Open("/_test/foo.txt")
        require.NoError(t, err)

        bytes, err := ioutil.ReadAll(file)
        assert.NoError(t, err)
        assert.EqualValues(t, "bar\n", string(bytes))

        info := file.Stat()
        assert.False(t, info.IsDir())
        assert.EqualValues(t, 4, info.Size())
        assert.EqualValues(t, time.Now().Year(), info.ModTime().Year())
        assert.EqualValues(t, time.Now().Month(), info.ModTime().Month())
}

func TestReadEmptyFile(t *testing.T) {
        client := getClient(t)

        touch(t, "/_test/emptyfile")

        file, err := client.Open("/_test/emptyfile")
        require.NoError(t, err)

        bytes, err := ioutil.ReadAll(file)
        assert.NoError(t, err)
        assert.EqualValues(t, "", string(bytes))
}

func TestFileBigRead(t *testing.T) {
        client := getClient(t)

        file, err := client.Open("/_test/mobydick.txt")
        require.NoError(t, err)

        hash := crc32.NewIEEE()
        n, err := io.Copy(hash, file)
        assert.NoError(t, err)
        assert.EqualValues(t, n, 1257276)
        assert.EqualValues(t, 0x199d1ae6, hash.Sum32())
}

func TestFileBigReadWeirdSizes(t *testing.T) {
        client := getClient(t)

        file, err := client.Open("/_test/mobydick.txt")
        require.NoError(t, err)

        hash := crc32.NewIEEE()
        copied := 0
        var n int64
        for err == nil {
                n, err = io.CopyN(hash, file, int64(rand.Intn(1000)))
                copied += int(n)
        }

        assert.EqualValues(t, io.EOF, err)
        assert.EqualValues(t, 0x199d1ae6, hash.Sum32())
        assert.EqualValues(t, copied, 1257276)
}

func TestFileBigReadN(t *testing.T) {
        client := getClient(t)

        file, err := client.Open("/_test/mobydick.txt")
        require.NoError(t, err)

        n, err := io.CopyN(ioutil.Discard, file, 1000000)
        assert.NoError(t, err)
        assert.EqualValues(t, n, 1000000)
}

func TestFileReadAt(t *testing.T) {
        client := getClient(t)

        file, err := client.Open("/_test/mobydick.txt")
        require.NoError(t, err)

        buf := make([]byte, len(testStr))
        off := 0
        for off < len(buf) {
                n, err := file.ReadAt(buf[off:], int64(testStrOff+off))
                assert.NoError(t, err)
                assert.True(t, n > 0)
                off += n
        }

        assert.EqualValues(t, string(buf), testStr)

        buf = make([]byte, len(testStr2))
        off = 0
        for off < len(buf) {
                n, err := file.ReadAt(buf[off:], int64(testStr2Off+off))
                assert.NoError(t, err)
                assert.True(t, n > 0)
                off += n
        }

        assert.EqualValues(t, testStr2, string(buf))
}

func TestFileSeek(t *testing.T) {
        client := getClient(t)

        file, err := client.Open("/_test/mobydick.txt")
        require.NoError(t, err)

        buf := new(bytes.Buffer)

        off, err := file.Seek(testStrOff, 0)
        assert.NoError(t, err)
        assert.EqualValues(t, testStrOff, off)

        n, err := io.CopyN(buf, file, int64(len(testStr)))
        assert.NoError(t, err)
        assert.EqualValues(t, len(testStr), n)
        assert.EqualValues(t, testStr, string(buf.Bytes()))

        // seek backwards and read it again
        off, err = file.Seek(-1*int64(len(testStr)), 1)
        assert.NoError(t, err)
        assert.EqualValues(t, testStrOff, off)

        buf.Reset()
        n, err = io.CopyN(buf, file, int64(len(testStr)))
        assert.NoError(t, err)
        assert.EqualValues(t, len(testStr), n)
        assert.EqualValues(t, testStr, string(buf.Bytes()))

        // now seek forward to another block and read a string
        off, err = file.Seek(testStr2NegativeOff, 2)
        assert.NoError(t, err)
        assert.EqualValues(t, testStr2Off, off)

        buf.Reset()
        n, err = io.CopyN(buf, file, int64(len(testStr2)))
        assert.NoError(t, err)
        assert.EqualValues(t, len(testStr2), n)
        assert.EqualValues(t, testStr2, string(buf.Bytes()))
}

func TestFileReadDir(t *testing.T) {
        client := getClient(t)

        mkdirp(t, "/_test/fulldir3")
        mkdirp(t, "/_test/fulldir3/dir")
        touch(t, "/_test/fulldir3/1")
        touch(t, "/_test/fulldir3/2")
        touch(t, "/_test/fulldir3/3")

        file, err := client.Open("/_test/fulldir3")
        require.NoError(t, err)

        res, err := file.Readdir(2)
        require.Equal(t, 2, len(res))
        assert.EqualValues(t, "1", res[0].Name())
        assert.EqualValues(t, "2", res[1].Name())

        res, err = file.Readdir(5)
        require.Equal(t, 2, len(res))
        assert.EqualValues(t, "3", res[0].Name())
        assert.EqualValues(t, "dir", res[1].Name())

        res, err = file.Readdir(0)
        require.Equal(t, 4, len(res))
        assert.EqualValues(t, "1", res[0].Name())
        assert.EqualValues(t, "2", res[1].Name())
        assert.EqualValues(t, "3", res[2].Name())
        assert.EqualValues(t, "dir", res[3].Name())
}

func TestFileReadDirnames(t *testing.T) {
        client := getClient(t)

        mkdirp(t, "/_test/fulldir4")
        mkdirp(t, "/_test/fulldir4/dir")
        touch(t, "/_test/fulldir4/1")
        touch(t, "/_test/fulldir4/2")
        touch(t, "/_test/fulldir4/3")

        file, err := client.Open("/_test/fulldir4")
        require.NoError(t, err)

        res, err := file.Readdirnames(0)
        require.Equal(t, 4, len(res))
        assert.EqualValues(t, []string{"1", "2", "3", "dir"}, res)
}

func TestOpenFileWithoutPermission(t *testing.T) {
        otherClient := getClientForUser(t, "other")

        mkdirp(t, "/_test/accessdenied")
        touch(t, "/_test/accessdenied/foo")

        file, err := otherClient.Open("/_test/accessdenied/foo")
        assert.Nil(t, file)
        assertPathError(t, err, "open", "/_test/accessdenied/foo", os.ErrPermission)
}

func TestFileChecksum(t *testing.T) {
        client := getClient(t)

        file, err := client.Open("/_test/foo.txt")
        require.NoError(t, err)

        checksum, err := file.Checksum()
        require.NoError(t, err)

        assert.EqualValues(t, testChecksum, hex.EncodeToString(checksum))
}`
	client, err := bblfsh.NewClient("127.0.0.1:9432")
	require.NoError(t, err)
	resp, err := client.NewParseRequest().
		Content(code).
		Language("Go").
		Do()
	require.NoError(t, err)

	_, err = tools.Filter(resp.UAST, xpath)
	require.NoError(t, err)
}
```

Example error (though it fails some times with other errors):

```
Assertion failed: (node), function UastFilter, file uast.cc, line 268.
SIGABRT: abort
PC=0x7fff7b632e3e m=8 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff7b632e3e
stack: frame={sp:0x700001f14d08, fp:0x0} stack=[0x700001e95290,0x700001f14e90)
0000700001f14c08:  0000000000000000  00007fff7b5b8e05 
0000700001f14c18:  00000000056e2000  0000000000000000 
0000700001f14c28:  00007fff7b5b8e64  0000700001f14c90 
0000700001f14c38:  00007fff7b7650d0  0000000000000000 
0000700001f14c48:  0000000000000000  00007fff7b5b8e05 
0000700001f14c58:  0000700001f14ca0  0000000000000002 
0000700001f14c68:  0000000005384fe6  0000000005384f95 
0000700001f14c78:  00000000056e2000  000000000000010c 
0000700001f14c88:  0000000005384f56  0000700001f14d70 
0000700001f14c98:  00007fff7b76507d  0000003000000030 
0000700001f14ca8:  0000700001f14d80  0000700001f14cc0 
0000700001f14cb8:  000000000000010c  0000000000000000 
0000700001f14cc8:  0000000005648a00  0000000005384f95 
0000700001f14cd8:  0000000005384fe6  0000000005384f56 
0000700001f14ce8:  000000000000010c  0000000005384fe6 
0000700001f14cf8:  0000700001f14d68  0000000005384f95 
0000700001f14d08: <00007fff7b771150  0000700001f15000 
0000700001f14d18:  0000700001f14d58  00000000056e2028 
0000700001f14d28:  00000000056e2000  000000000000010c 
0000700001f14d38:  0000000005384f56  0000700001f14d70 
0000700001f14d48:  00007fff7b58f312  0000700001f14d70 
0000700001f14d58:  00007fffffffffdf  ffffffff00000000 
0000700001f14d68:  0000000005384fe6  0000700001f14db0 
0000700001f14d78:  00007fff7b557368  000000c420a96000 
0000700001f14d88:  000000000570bfc0  ffffffffffffffff 
0000700001f14d98:  000000000000028f  0000000006500000 
0000700001f14da8:  0000000000000000  0000700001f14e00 
0000700001f14db8:  000000000477db08  0000700001f14df0 
0000700001f14dc8:  00007fff7b68b201  0000000000000028 
0000700001f14dd8:  0000000000000028  000000c420a95ed0 
0000700001f14de8:  ffffffffffffffff  000000c420a96000 
0000700001f14df8:  000000c420a95ed0  0000700001f14e30 
runtime: unknown pc 0x7fff7b632e3e
stack: frame={sp:0x700001f14d08, fp:0x0} stack=[0x700001e95290,0x700001f14e90)
0000700001f14c08:  0000000000000000  00007fff7b5b8e05 
0000700001f14c18:  00000000056e2000  0000000000000000 
0000700001f14c28:  00007fff7b5b8e64  0000700001f14c90 
0000700001f14c38:  00007fff7b7650d0  0000000000000000 
0000700001f14c48:  0000000000000000  00007fff7b5b8e05 
0000700001f14c58:  0000700001f14ca0  0000000000000002 
0000700001f14c68:  0000000005384fe6  0000000005384f95 
0000700001f14c78:  00000000056e2000  000000000000010c 
0000700001f14c88:  0000000005384f56  0000700001f14d70 
0000700001f14c98:  00007fff7b76507d  0000003000000030 
0000700001f14ca8:  0000700001f14d80  0000700001f14cc0 
0000700001f14cb8:  000000000000010c  0000000000000000 
0000700001f14cc8:  0000000005648a00  0000000005384f95 
0000700001f14cd8:  0000000005384fe6  0000000005384f56 
0000700001f14ce8:  000000000000010c  0000000005384fe6 
0000700001f14cf8:  0000700001f14d68  0000000005384f95 
0000700001f14d08: <00007fff7b771150  0000700001f15000 
0000700001f14d18:  0000700001f14d58  00000000056e2028 
0000700001f14d28:  00000000056e2000  000000000000010c 
0000700001f14d38:  0000000005384f56  0000700001f14d70 
0000700001f14d48:  00007fff7b58f312  0000700001f14d70 
0000700001f14d58:  00007fffffffffdf  ffffffff00000000 
0000700001f14d68:  0000000005384fe6  0000700001f14db0 
0000700001f14d78:  00007fff7b557368  000000c420a96000 
0000700001f14d88:  000000000570bfc0  ffffffffffffffff 
0000700001f14d98:  000000000000028f  0000000006500000 
0000700001f14da8:  0000000000000000  0000700001f14e00 
0000700001f14db8:  000000000477db08  0000700001f14df0 
0000700001f14dc8:  00007fff7b68b201  0000000000000028 
0000700001f14dd8:  0000000000000028  000000c420a95ed0 
0000700001f14de8:  ffffffffffffffff  000000c420a96000 
0000700001f14df8:  000000c420a95ed0  0000700001f14e30 

goroutine 5 [syscall]:
runtime.cgocall(0x477ca60, 0xc420a95ed0, 0x0)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/cgocall.go:128 +0x64 fp=0xc420a95e90 sp=0xc420a95e58 pc=0x4003954
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools._Cfunc_Filter(0x0, 0x6500000, 0x0)
	_cgo_gotypes.go:107 +0x4a fp=0xc420a95ed0 sp=0xc420a95e90 pc=0x46f680a
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools.Filter(0x0, 0x4a84dbc, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools/bindings.go:119 +0xbd fp=0xc420a95f48 sp=0xc420a95ed0 pc=0x46f79fd
github.com/src-d/gitbase/internal/function.TestBblfshFailing(0xc42025c2d0)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/internal/function/uast_test.go:408 +0x15e fp=0xc420a95fa8 sp=0xc420a95f48 pc=0x477911e
testing.tRunner(0xc42025c2d0, 0x4aa46b8)
	/usr/local/Cellar/go/1.10.1/libexec/src/testing/testing.go:777 +0xd0 fp=0xc420a95fd0 sp=0xc420a95fa8 pc=0x40ee6b0
runtime.goexit()
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420a95fd8 sp=0xc420a95fd0 pc=0x405b121
created by testing.(*T).Run
	/usr/local/Cellar/go/1.10.1/libexec/src/testing/testing.go:824 +0x2e0

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42025c2d0, 0x4a20124, 0x11, 0x4aa46b8, 0x407c801)
	/usr/local/Cellar/go/1.10.1/libexec/src/testing/testing.go:825 +0x301
testing.runTests.func1(0xc42025c1e0)
	/usr/local/Cellar/go/1.10.1/libexec/src/testing/testing.go:1063 +0x64
testing.tRunner(0xc42025c1e0, 0xc4201b3df8)
	/usr/local/Cellar/go/1.10.1/libexec/src/testing/testing.go:777 +0xd0
testing.runTests(0xc420a5a8e0, 0x53e0aa0, 0x6, 0x6, 0x4012919)
	/usr/local/Cellar/go/1.10.1/libexec/src/testing/testing.go:1061 +0x2c4
testing.(*M).Run(0xc420471080, 0x0)
	/usr/local/Cellar/go/1.10.1/libexec/src/testing/testing.go:978 +0x171
main.main()
	_testmain.go:52 +0x151

goroutine 6 [select]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc420a319b0)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:108 +0x182
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*ccResolverWrapper).start
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:94 +0x3f

goroutine 7 [select]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc420031480)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x14a
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x14c

goroutine 8 [select]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc420a9a000)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/clientconn.go:1224 +0x235
github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc420a9a000)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/clientconn.go:827 +0x1b5
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc.(*addrConn).connect
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/clientconn.go:818 +0xe1

goroutine 36 [IO wait]:
internal/poll.runtime_pollWait(0x62e8f60, 0x72, 0xc420070bb8)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420471218, 0x72, 0xffffffffffffff00, 0x4bb6660, 0x5386cc0)
	/usr/local/Cellar/go/1.10.1/libexec/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420471218, 0xc420aa4000, 0x8000, 0x8000)
	/usr/local/Cellar/go/1.10.1/libexec/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420471200, 0xc420aa4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.1/libexec/src/internal/poll/fd_unix.go:157 +0x1dc
net.(*netFD).Read(0xc420471200, 0xc420aa4000, 0x8000, 0x8000, 0x11, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42000e008, 0xc420aa4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/net.go:176 +0x6a
bufio.(*Reader).Read(0xc420a9e060, 0xc420ab6038, 0x9, 0x9, 0x9, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.1/libexec/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x4bb3ba0, 0xc420a9e060, 0xc420ab6038, 0x9, 0x9, 0x9, 0xc420070df0, 0x40028be, 0xc420070e9f)
	/usr/local/Cellar/go/1.10.1/libexec/src/io/io.go:309 +0x86
io.ReadFull(0x4bb3ba0, 0xc420a9e060, 0xc420ab6038, 0x9, 0x9, 0x45de75d, 0xc420a9c0ac, 0xc420044300)
	/usr/local/Cellar/go/1.10.1/libexec/src/io/io.go:327 +0x58
github.com/src-d/gitbase/vendor/golang.org/x/net/http2.readFrameHeader(0xc420ab6038, 0x9, 0x9, 0x4bb3ba0, 0xc420a9e060, 0x0, 0x0, 0x53ed660, 0xbec34e093548e55d)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/src-d/gitbase/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc420ab6000, 0xc420a9c0a0, 0xc420a9c0a0, 0x0, 0x0)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc42008ed80)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:1195 +0xe1
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:273 +0xbf1

goroutine 37 [select]:
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.loopyWriter(0x4bc2840, 0xc420031540, 0xc420aa0180, 0xc420071fb8)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/transport.go:748 +0x368
github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client.func3(0xc42008ed80)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:305 +0x5e
created by github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/google.golang.org/grpc/transport/http2_client.go:304 +0xd42

rax    0x0
rbx    0x700001f15000
rcx    0x700001f14d08
rdx    0x0
rdi    0x2503
rsi    0x6
rbp    0x700001f14d40
rsp    0x700001f14d08
r8     0x0
r9     0x0
r10    0x0
r11    0x206
r12    0x2503
r13    0x56e2000
r14    0x6
r15    0x2d
rip    0x7fff7b632e3e
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
```

And:

```
unexpected fault address 0xc4d000198bd
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc4d000198bd pc=0x4674363]

goroutine 5 [running]:
runtime.throw(0x4b67faf, 0x5)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/panic.go:616 +0x81 fp=0xc4221c95b0 sp=0xc4221c9590 pc=0x402d8b1
runtime.sigpanic()
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/signal_unix.go:395 +0x211 fp=0xc4221c9600 sp=0xc4221c95b0 pc=0x4042fb1
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast.(*Node).ProtoSize(0xc421226c40, 0x1)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast/generated.pb.go:440 +0x53 fp=0xc4221c96f0 sp=0xc4221c9600 pc=0x4674363
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast.(*Node).ProtoSize(0xc420fd6460, 0x1)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast/generated.pb.go:450 +0x91 fp=0xc4221c97e0 sp=0xc4221c96f0 pc=0x46743a1
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast.(*Node).ProtoSize(0xc420fd63f0, 0x2)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast/generated.pb.go:450 +0x91 fp=0xc4221c98d0 sp=0xc4221c97e0 pc=0x46743a1
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast.(*Node).ProtoSize(0xc420fd6150, 0xc421674e00)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast/generated.pb.go:450 +0x91 fp=0xc4221c99c0 sp=0xc4221c98d0 pc=0x46743a1
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast.(*Node).Marshal(0xc420fd6150, 0xc4221c9bc0, 0x49ab820, 0xc4216c6360, 0x0, 0x0)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast/generated.pb.go:296 +0x2f fp=0xc4221c9a18 sp=0xc4221c99c0 pc=0x46733cf
```

And:

```
fatal error: concurrent map iteration and map write

goroutine 5 [running, locked to thread]:
runtime.throw(0x4c65d8f, 0x26)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/panic.go:616 +0x81 fp=0xc421387650 sp=0xc421387630 pc=0x402d961
runtime.mapiternext(0xc421387778)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/hashmap.go:747 +0x55c fp=0xc4213876e0 sp=0xc421387650 pc=0x400b8fc
runtime.mapiterinit(0x4a16ce0, 0xc4213e8562, 0xc421387778)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/hashmap.go:737 +0x1f1 fp=0xc421387708 sp=0xc4213876e0 pc=0x400b2b1
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools.goGetPropertyKey(0xc421503f80, 0x0, 0xc421387820)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools/bindings.go:239 +0x79 fp=0xc4213877e8 sp=0xc421387708 pc=0x4899149
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools._cgoexpwrap_c8b38fe99d54_goGetPropertyKey(0xc421503f80, 0x0, 0x0)
	_cgo_gotypes.go:340 +0x62 fp=0xc421387810 sp=0xc4213877e8 pc=0x4898382
runtime.call32(0x0, 0x70000a91e520, 0x70000a91e5b0, 0x18)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/asm_amd64.s:573 +0x3b fp=0xc421387840 sp=0xc421387810 pc=0x405908b
runtime.cgocallbackg1(0x0)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/cgocall.go:316 +0x19c fp=0xc4213878c0 sp=0xc421387840 pc=0x400441c
runtime.cgocallbackg(0x0)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/cgocall.go:194 +0xda fp=0xc421387928 sp=0xc4213878c0 pc=0x40041ea
runtime.cgocallback_gofunc(0x4004098, 0x490b980, 0xc4213879c8, 0x56c1480)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/asm_amd64.s:826 +0x9b fp=0xc421387948 sp=0xc421387928 pc=0x405a65b
runtime.asmcgocall(0x490b980, 0xc4213879c8)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/asm_amd64.s:673 +0x42 fp=0xc421387950 sp=0xc421387948 pc=0x405a4f2
runtime.cgocall(0x490b980, 0xc4213879c8, 0x0)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/cgocall.go:131 +0x88 fp=0xc421387988 sp=0xc421387950 pc=0x4004098
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools._Cfunc_Filter(0xc4214ef030, 0x6bfbb00, 0x0)
	_cgo_gotypes.go:107 +0x4a fp=0xc4213879c8 sp=0xc421387988 pc=0x4897c8a
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools.Filter(0xc4214ef030, 0xc420037d10, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools/bindings.go:119 +0xbd fp=0xc421387a40 sp=0xc4213879c8 pc=0x4898e7d
```

And: 

```
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x400b83a]

goroutine 22 [running]:
runtime.throw(0x4b67faf, 0x5)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/panic.go:616 +0x81 fp=0xc42102b700 sp=0xc42102b6e0 pc=0x402d961
runtime.sigpanic()
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/signal_unix.go:395 +0x211 fp=0xc42102b750 sp=0xc42102b700 pc=0x4043061
runtime.evacuated(...)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/hashmap.go:198
runtime.mapiternext(0xc42102b888)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/hashmap.go:771 +0x49a fp=0xc42102b7e0 sp=0xc42102b750 pc=0x400b83a
runtime.mapiterinit(0x4a16ce0, 0xc4214d9b80, 0xc42102b888)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/hashmap.go:737 +0x1f1 fp=0xc42102b808 sp=0xc42102b7e0 pc=0x400b2b1
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast.(*Node).ProtoSize(0xc420b21500, 0x1)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast/generated.pb.go:441 +0x2b5 fp=0xc42102b8f8 sp=0xc42102b808 pc=0x4674675
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast.(*Node).ProtoSize(0xc42162f570, 0x16)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast/generated.pb.go:450 +0x91 fp=0xc42102b9e8 sp=0xc42102b8f8 pc=0x4674451
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast.(*Node).Marshal(0xc42162f570, 0x0, 0x16, 0xc42121e2c0, 0x0, 0x16)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/sdk.v1/uast/generated.pb.go:296 +0x2f fp=0xc42102ba40 sp=0xc42102b9e8 pc=0x467347f
```

**Comment by dennwc** [comment]
Found multiple problems in the test case:

* Test refers to language driver as "Go" instead of "go" and forgets to check the status in the response. The client will now return a Go error in case Fatal status is returned (as in this case).

* Test passes a nil node pointer to the filter function (because parsing failed initially). The client will now check for this case.

Looking at the [original issue](https://github.com/src-d/gitbase/issues/329) it seems we need another reproducer. But I also found a bug in the C string pool that is referenced in the original stack trace. So #62 might actually fix this panic.
