### ISSUE TITLE
panic: unexpected fault address

### ISSUE THREAD

**Issue by erizocosmico** [bblfsh/client-go#72]
After the fix in 2.8.0 for #69 this new panic appears:

```
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x4057fe5]

goroutine 50 [running, locked to thread]:
runtime.throw(0x4b1f0bb, 0x5)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/panic.go:616 +0x81 fp=0xc42127d398 sp=0xc42127d378 pc=0x402c011
runtime.sigpanic()
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/signal_unix.go:395 +0x211 fp=0xc42127d3e8 sp=0xc42127d398 pc=0x4040b81
runtime.memmove(0x122df000, 0x6c616e7265746e69, 0x40000000)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/memmove_amd64.s:389 +0x485 fp=0xc42127d3f0 sp=0xc42127d3e8 pc=0x4057fe5
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools._Cfunc_CString(0x6c616e7265746e69, 0x656c6f52, 0x0)
	_cgo_gotypes.go:72 +0x65 fp=0xc42127d420 sp=0xc42127d3f0 pc=0x47c5e05
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools.(*cstringPool).getCstring(0x567de60, 0x6c616e7265746e69, 0x656c6f52, 0xc42127d4b0)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools/cstring_pool.go:12 +0x39 fp=0xc42127d478 sp=0xc42127d420 pc=0x47c77f9
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools.goGetInternalType(0xc420b9c9e0, 0x4c3dfa8)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools/bindings.go:204 +0x43 fp=0xc42127d4a8 sp=0xc42127d478 pc=0x47c72f3
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools._cgoexpwrap_41f7380b1fa0_goGetInternalType(0xc420b9c9e0, 0x0)
	_cgo_gotypes.go:243 +0x5a fp=0xc42127d4d0 sp=0xc42127d4a8 pc=0x47c61ca
runtime.call32(0x0, 0x7000014f87b0, 0x7000014f8840, 0x10)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/asm_amd64.s:573 +0x3b fp=0xc42127d500 sp=0xc42127d4d0 pc=0x4054b2b
runtime.cgocallbackg1(0x0)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/cgocall.go:316 +0x19c fp=0xc42127d580 sp=0xc42127d500 pc=0x4003e8c
runtime.cgocallbackg(0x0)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/cgocall.go:194 +0xda fp=0xc42127d5e8 sp=0xc42127d580 pc=0x4003c5a
runtime.cgocallback_gofunc(0x4003b08, 0x48bcdc0, 0xc42127d688, 0xc42118b6a0)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/asm_amd64.s:826 +0x9b fp=0xc42127d608 sp=0xc42127d5e8 pc=0x40560fb
runtime.asmcgocall(0x48bcdc0, 0xc42127d688)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/asm_amd64.s:673 +0x42 fp=0xc42127d610 sp=0xc42127d608 pc=0x4055f92
runtime.cgocall(0x48bcdc0, 0xc42127d688, 0x0)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/cgocall.go:131 +0x88 fp=0xc42127d648 sp=0xc42127d610 pc=0x4003b08
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools._Cfunc_Filter(0xc4211fb110, 0x83001d0, 0x0)
	_cgo_gotypes.go:107 +0x4a fp=0xc42127d688 sp=0xc42127d648 pc=0x47c5f5a
github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools.Filter(0xc4211fb110, 0xc420228200, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/erizocosmico/go/src/github.com/src-d/gitbase/vendor/gopkg.in/bblfsh/client-go.v2/tools/bindings.go:122 +0xc4 fp=0xc42127d700 sp=0xc42127d688 pc=0x47c7114
```

Previously we used to `recover` in the UAST function of gitbase just to not make the server crash after a bblfsh panic. This one was not caught by the recover.

**Comment by dennwc** [comment]
Is there a specific case that can reproduce it? Maybe a specific file?

**Comment by erizocosmico** [comment]
I'll try to get the specific file that causes this

**Comment by erizocosmico** [comment]
It turns out it was my fault, didn't notice dep ensure failed and was not updated. Now it works well :+1:
